name: C2ME Build Script

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 23
          java-package: jdk

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - name: Install required dependencies
        run: sudo apt update && sudo apt install libtinfo5

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle4-test-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle4-test-

      - name: setup project
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./build.sh up
          ./build.sh patch

      - name: build
        run: |
          cd C2ME-fabric-patched
          ./gradlew clean build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            C2ME-fabric-patched/build/libs/

